apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: demo          # 설명: Deployment와 동일 네임스페이스
spec:
  type: ClusterIP          # 설명: 내부 서비스(외부는 Ingress/ALB가 담당)
  selector:
    app: web               # 설명: deployment의 pod 라벨과 일치해야 함
  ports:
    - port: 80             # 설명: 서비스 포트
      targetPort: 80       # 설명: 파드 컨테이너 포트
